layout: {qmk_keyboard: corne_rotated, layout_name: LAYOUT_split_3x5_3}
layers:
  base:
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ''''
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - I
  - O
  - {t: Z, h: CTRL}
  - {t: X, h: SHIFT}
  - {t: C, h: GUI}
  - {t: D, h: ALT}
  - V
  - K
  - {t: H, h: ALT}
  - {t: ',', h: GUI, s: ;}
  - {t: ., h: SHIFT, s: ':"'}
  - {t: '?', h: CTRL, s: '!'}
  - {t: CTRL, h: num}
  - {t: SPACE, h: nav}
  - sys
  - fn
  - {t: SHIFT, h: sticky, s: '&caps_word'}
  - TAB
  nav:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PG UP
  - HOME
  - UP
  - END
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PG DN
  - LEFT
  - DOWN
  - RIGHT
  - {t: ▽, type: trans}
  - {t: CTRL, h: sticky}
  - {t: SHIFT, h: sticky}
  - {t: GUI, h: sticky}
  - {t: ALT, h: sticky}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  fn:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F12
  - F7
  - F8
  - F9
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F11
  - F4
  - F5
  - F6
  - {t: ▽, type: trans}
  - {t: CTRL, h: sticky}
  - {t: SHIFT, h: sticky}
  - {t: GUI, h: sticky}
  - {t: ALT, h: sticky}
  - {t: ▽, type: trans}
  - F10
  - F1
  - F2
  - F3
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  num:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '7'
  - '8'
  - '9'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '4'
  - '5'
  - '6'
  - {t: ▽, type: trans}
  - {t: CTRL, h: sticky}
  - {t: SHIFT, h: sticky}
  - {t: GUI, h: sticky}
  - {t: ALT, h: sticky}
  - {t: ▽, type: trans}
  - '0'
  - '1'
  - '2'
  - '3'
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  sys:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PSCRN
  - MUTE
  - VOL DN
  - VOL UP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
combos:
- p: [3, 2]
  k: BSPC
  l: [base, nav, num]
- p: [2, 1]
  k: DEL
  l: [base, nav, num]
- p: [3, 4]
  k: Ctl+ Z
  l: [base, nav, num]
- p: [11, 12]
  k: ESC
  l: [base, nav, num]
- p: [12, 13]
  k: RETURN
  l: [base, nav, num]
- p: [13, 14]
  k: Ctl+ Y
  l: [base, nav, num]
- p: [21, 23]
  k: Ctl+ X
  l: [base, nav, num]
- p: [21, 22]
  k: Ctl+ INS
  l: [base, nav, num]
- p: [22, 23]
  k: Sft+ INS
  l: [base, nav, num]
- p: [6, 7]
  k: BSPC
  l: [base, nav, num]
- p: [7, 8]
  k: DEL
  l: [base, nav, num]
- p: [16, 17]
  k: {t: (, s: <}
  l: [base, num]
- p: [17, 18]
  k: {t: ), s: '>'}
  l: [base, num]
- p: [16, 17]
  k: <
  l: [nav]
- p: [17, 18]
  k: '>'
  l: [nav]
- p: [26, 27]
  k: '['
  l: [base, num]
- p: [27, 28]
  k: ']'
  l: [base, num]
- p: [26, 27]
  k: '{'
  l: [nav]
- p: [27, 28]
  k: '}'
  l: [nav]
- p: [1, 11]
  k: '@'
  l: [base, nav, num]
- p: [2, 12]
  k: '#'
  l: [base, nav, num]
- p: [3, 13]
  k: $
  l: [base, nav, num]
- p: [4, 14]
  k: '%'
  l: [base, nav, num]
- p: [11, 21]
  k: '`'
  l: [base, nav, num]
- p: [12, 22]
  k: \
  l: [base, nav, num]
- p: [13, 23]
  k: '='
  l: [base, nav, num]
- p: [14, 24]
  k: '~'
  l: [base, nav, num]
- p: [5, 15]
  k: ^
  l: [base, nav, num]
- p: [6, 16]
  k: +
  l: [base, nav, num]
- p: [7, 17]
  k: '*'
  l: [base, nav, num]
- p: [8, 18]
  k: '&'
  l: [base, nav, num]
- p: [16, 26]
  k: {t: '-', s: _}
  l: [base, nav, num]
- p: [15, 25]
  k: /
  l: [base, nav, num]
- p: [18, 28]
  k: '|'
  l: [base, nav, num]
